// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260813182954_AddGuestModuleTables")]
    partial class AddGuestModuleTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagementSystem.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CartItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SessionId", "ProductID")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GymManagementSystem.Models.ContactMessage", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ContactID");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("GymManagementSystem.Models.FaqItem", b =>
                {
                    b.Property<int>("FaqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqID"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqID");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqID = 1,
                            Answer = "Our gym is open 24/7 for premium members. Standard hours are Monday to Saturday from 5:00 AM to 11:00 PM.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Question = "What are your gym hours?"
                        },
                        new
                        {
                            FaqID = 2,
                            Answer = "No, we provide all state-of-the-art gym equipment, mats, and accessories. Just bring a water bottle and athletic shoes!",
                            DisplayOrder = 2,
                            IsActive = true,
                            Question = "Do I need to bring my own equipment?"
                        },
                        new
                        {
                            FaqID = 3,
                            Answer = "Yes, you can pause or freeze your active membership for up to 3 months per year through our reception or online dashboard.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Question = "Can I freeze my membership?"
                        },
                        new
                        {
                            FaqID = 4,
                            Answer = "Yes! We have certified personal trainers available for 1-on-1 sessions included in Standard and Premium plans.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Question = "Do you offer personal training?"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.GalleryImage", b =>
                {
                    b.Property<int>("GalleryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryID");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            GalleryID = 1,
                            DisplayOrder = 1,
                            ImageURL = "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            Title = "Heavy Lifting"
                        },
                        new
                        {
                            GalleryID = 2,
                            DisplayOrder = 2,
                            ImageURL = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            Title = "Cardio Session"
                        },
                        new
                        {
                            GalleryID = 3,
                            DisplayOrder = 3,
                            ImageURL = "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            Title = "Modern Equipment"
                        },
                        new
                        {
                            GalleryID = 4,
                            DisplayOrder = 4,
                            ImageURL = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            Title = "Personal Training"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.GuestOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("GuestOrders");
                });

            modelBuilder.Entity("GymManagementSystem.Models.GuestOrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("GuestOrderItems");
                });

            modelBuilder.Entity("GymManagementSystem.Models.GymClass", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassID");

                    b.ToTable("GymClasses");

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            ClassName = "Strength & Lifting",
                            Days = "Mon, Wed, Fri",
                            Icon = "dumbbell",
                            ImageUrl = "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            TimeSlot = "08:00 AM - 10:00 AM",
                            TrainerName = "John Doe"
                        },
                        new
                        {
                            ClassID = 2,
                            ClassName = "Cardio & Burn",
                            Days = "Tue, Thu, Sat",
                            Icon = "activity",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            TimeSlot = "10:00 AM - 11:30 AM",
                            TrainerName = "Jane Smith"
                        },
                        new
                        {
                            ClassID = 3,
                            ClassName = "CrossFit Pro",
                            Days = "Mon, Wed, Fri",
                            Icon = "target",
                            ImageUrl = "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1000&q=80",
                            IsActive = true,
                            TimeSlot = "04:00 PM - 06:00 PM",
                            TrainerName = "Mike Johnson"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.MembershipPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanID");

                    b.ToTable("MembershipPlans");

                    b.HasData(
                        new
                        {
                            PlanID = 1,
                            DisplayOrder = 1,
                            DurationInMonths = 1,
                            IsActive = true,
                            Price = 29.99m,
                            Title = "Standard Plan"
                        },
                        new
                        {
                            PlanID = 2,
                            DisplayOrder = 2,
                            DurationInMonths = 1,
                            IsActive = true,
                            Price = 49.99m,
                            Title = "Pro Plan"
                        },
                        new
                        {
                            PlanID = 3,
                            DisplayOrder = 3,
                            DurationInMonths = 1,
                            IsActive = true,
                            Price = 89.99m,
                            Title = "VIP Elite"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.MembershipPlanFeature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.HasKey("FeatureID");

                    b.HasIndex("PlanID");

                    b.ToTable("MembershipPlanFeatures");

                    b.HasData(
                        new
                        {
                            FeatureID = 1,
                            Description = "Access to gym equipment",
                            DisplayOrder = 1,
                            PlanID = 1
                        },
                        new
                        {
                            FeatureID = 2,
                            Description = "Locker room access",
                            DisplayOrder = 2,
                            PlanID = 1
                        },
                        new
                        {
                            FeatureID = 3,
                            Description = "1 Free guest pass per month",
                            DisplayOrder = 3,
                            PlanID = 1
                        },
                        new
                        {
                            FeatureID = 4,
                            Description = "Standard support",
                            DisplayOrder = 4,
                            PlanID = 1
                        },
                        new
                        {
                            FeatureID = 5,
                            Description = "24/7 Gym access",
                            DisplayOrder = 1,
                            PlanID = 2
                        },
                        new
                        {
                            FeatureID = 6,
                            Description = "Unlimited guest passes",
                            DisplayOrder = 2,
                            PlanID = 2
                        },
                        new
                        {
                            FeatureID = 7,
                            Description = "Free personal trainer (2 sessions)",
                            DisplayOrder = 3,
                            PlanID = 2
                        },
                        new
                        {
                            FeatureID = 8,
                            Description = "Nutrition guidance",
                            DisplayOrder = 4,
                            PlanID = 2
                        },
                        new
                        {
                            FeatureID = 9,
                            Description = "Priority support",
                            DisplayOrder = 5,
                            PlanID = 2
                        },
                        new
                        {
                            FeatureID = 10,
                            Description = "All Pro Plan features",
                            DisplayOrder = 1,
                            PlanID = 3
                        },
                        new
                        {
                            FeatureID = 11,
                            Description = "Dedicated 1-on-1 personal trainer",
                            DisplayOrder = 2,
                            PlanID = 3
                        },
                        new
                        {
                            FeatureID = 12,
                            Description = "Custom meal & diet plans",
                            DisplayOrder = 3,
                            PlanID = 3
                        },
                        new
                        {
                            FeatureID = 13,
                            Description = "VIP lounge & sauna access",
                            DisplayOrder = 4,
                            PlanID = 3
                        },
                        new
                        {
                            FeatureID = 14,
                            Description = "Free protein shakes",
                            DisplayOrder = 5,
                            PlanID = 3
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Supplements",
                            Description = "Fast absorbing whey protein isolate, 2kg.",
                            IsActive = true,
                            Price = 59.99m,
                            ProductImage = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80",
                            ProductName = "Whey Protein Isolate",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Accessories",
                            Description = "700ml leak proof shaker bottle.",
                            IsActive = true,
                            Price = 12.50m,
                            ProductImage = "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=500&q=80",
                            ProductName = "Gym Shaker Bottle",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Equipment",
                            Description = "Pair of adjustable dumbbells, 2.5kg - 24kg.",
                            IsActive = true,
                            Price = 120.00m,
                            ProductImage = "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=500&q=80",
                            ProductName = "Adjustable Dumbbells",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Equipment",
                            Description = "Set of 5 resistance bands with carry bag.",
                            IsActive = true,
                            Price = 24.99m,
                            ProductImage = "https://images.unsplash.com/photo-1598289431512-b97b09177c42?auto=format&fit=crop&w=500&q=80",
                            ProductName = "Resistance Bands Set",
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Testimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialID"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MemberImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("TestimonialID");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialID = 1,
                            Feedback = "Joining FitZone completely changed my lifestyle. The trainers are certified and professional, and the equipment is top-notch!",
                            IsApproved = true,
                            MemberImage = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
                            MemberName = "Ahmed Mohamed",
                            Rating = 5
                        },
                        new
                        {
                            TestimonialID = 2,
                            Feedback = "The atmosphere is extremely motivating. I've lost over 10kg and gained so much strength thanks to the personalized workout plan.",
                            IsApproved = true,
                            MemberImage = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
                            MemberName = "Amina Ali",
                            Rating = 5
                        },
                        new
                        {
                            TestimonialID = 3,
                            Feedback = "Best gym in town hands down! Clean facilities, friendly staff, and the supplement store has everything I need after a heavy workout.",
                            IsApproved = true,
                            MemberImage = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
                            MemberName = "Liban Hassan",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.TrainerProfile", b =>
                {
                    b.Property<int>("TrainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerID");

                    b.ToTable("TrainerProfiles");

                    b.HasData(
                        new
                        {
                            TrainerID = 1,
                            DisplayOrder = 1,
                            Experience = "8 Years Experience",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
                            IsActive = true,
                            Role = "Head Strength Coach",
                            TrainerName = "Sarah Jenkins"
                        },
                        new
                        {
                            TrainerID = 2,
                            DisplayOrder = 2,
                            Experience = "5 Years Experience",
                            ImageUrl = "https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=600&q=80",
                            IsActive = true,
                            Role = "CrossFit & Conditioning",
                            TrainerName = "David Miller"
                        },
                        new
                        {
                            TrainerID = 3,
                            DisplayOrder = 3,
                            Experience = "6 Years Experience",
                            ImageUrl = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=600&q=80",
                            IsActive = true,
                            Role = "Personal Fitness Trainer",
                            TrainerName = "Alex Turner"
                        },
                        new
                        {
                            TrainerID = 4,
                            DisplayOrder = 4,
                            Experience = "7 Years Experience",
                            ImageUrl = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
                            IsActive = true,
                            Role = "Yoga & Mobility Specialist",
                            TrainerName = "Jessica Wong"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymManagementSystem.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("GymManagementSystem.Models.CartItem", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymManagementSystem.Models.GuestOrderItem", b =>
                {
                    b.HasOne("GymManagementSystem.Models.GuestOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GymManagementSystem.Models.MembershipPlanFeature", b =>
                {
                    b.HasOne("GymManagementSystem.Models.MembershipPlan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GymManagementSystem.Models.GuestOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GymManagementSystem.Models.MembershipPlan", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
